name: sourcepoint_unified_cmp_ios
description: flutter plugin for the sourcepoint unified CMP,
  with integrations for Android and iOS - iOS implementation
version: 0.1.11+2
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp/tree/main/packages/sourcepoint_unified_cmp_ios

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: sourcepoint_unified_cmp
    platforms:
      ios:
        pluginClass: SourcepointUnifiedCmpPlugin
        dartPluginClass: SourcepointUnifiedCmpIOS

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp_platform_interface: ^0.1.11+2

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  pigeon: ">=16.0.0 <18.0.0"
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^5.1.0
