name: sourcepoint_unified_cmp
description: flutter plugin for the sourcepoint unified CMP,
  with integrations for Android and iOS
version: 0.1.10+1
homepage: https://github.com/thekorn/sourcepoint_unified_cmp
repository: https://github.com/thekorn/sourcepoint_unified_cmp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: sourcepoint_unified_cmp_android
      ios:
        default_package: sourcepoint_unified_cmp_ios

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp_android: ^0.1.10+1
  sourcepoint_unified_cmp_ios: ^0.1.10+1
  sourcepoint_unified_cmp_platform_interface: ^0.1.10+1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.6
  very_good_analysis: ^5.1.0
