name: sourcepoint_unified_cmp_flutter_webview_extension_example
description: Demonstrates how to use the sourcepoint_unified_cmp_flutter_webview_extension extension.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp:
    # When depending on this package from a real application you should use:
    #   sourcepoint_unified_cmp: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../../sourcepoint_unified_cmp
  sourcepoint_unified_cmp_flutter_webview_extension:
    # When depending on this package from a real application you should use:
    #   sourcepoint_unified_cmp_flutter_webview_extension: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  webview_flutter: ^4.7.0

dev_dependencies:
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
