name: sourcepoint_unified_cmp_example
description: Demonstrates how to use the sourcepoint_unified_cmp plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sourcepoint_unified_cmp:
    # When depending on this package from a real application you should use:
    #   sourcepoint_unified_cmp: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
